### ISSUE TITLE
Transaction details show `WETH` symbol

### ISSUE THREAD

**Issue by lykalabrada** [DeFiCh/metascan#249]
#### What happened:
Swapped DFI and VAN using https://vanillaswap.org/#/swap, displayed token symbol on the transaction details is showing `WETH` instead of `DFI`. Can refer to [this tx](https://meta.defiscan.live/tx/0x55b25834a6fc1dc6ceccfa324894d53f4d30d77dbd33842e56a7353c16103aea)

#### What you expected to happen:
Should see `DFI` instead `WETH` in the toke transfers section

#### Anything else we need to know?:
![image](https://github.com/BirthdayResearch/metascan/assets/17063281/bbc69aa8-31e2-49be-b3be-8faa349826a2)
![image](https://github.com/BirthdayResearch/metascan/assets/17063281/aacd8764-0cec-4a4c-987f-74abe8ab420e)

**Comment by pierregee** [comment]
I was checking the WETH issue and all data seems to be correct. Consulted with an expert, @cuongquangnam! 
This is correct
1. The token swapping mechanism needed to use wrapped eth (WETH) to send VAN token
2. The naming of the token WETH is in the smart contract level
